### ISSUE TITLE
Unclear how to start tutorial example

### ISSUE THREAD

**Issue by ysangkok** [agocorona/transient#21]
After removing the n (#20) I start the server using `stack runghc app/Main.hs`. I open my browser at localhost:8081, and it says it can't find Index.html (I wrote a comment on a commit for that). How do I launch the example from the bottom of the tutorial?

**Comment by geraldus** [comment]
You need to compile code with GHCJS first and copy produced `Main.jsexe` folder to `<project root>/static/out.jsexe` if I'm not mistaken.  To make this work with stack you may need something similar in your `stack.yaml` configuration:

```yaml
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
         url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
         sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```

If I'm not mistaken with this config you'll be able to install GHCJS first by running `stack setup --compiler=ghcjs-0.2.0_ghc-7.10.3` from project root and after GHCJS will be booted you can build your project with GHCJS via `stack build --compiler=ghcjs-0.2.0_ghc-7.10.3`.

Hope this helps.
